#
# CSE 5441 : Lab 2
# Filename : makefile
# Author   : Rajarshi Biswas (biswas.91@osu.edu)
#	     The Ohio State University.

all: biswas_rajarshi_disposable 

biswas_rajarshi_disposable: biswas_rajarshi_disposable.cc
	g++ -std=gnu++0x -O3 -pthread  -o disposable biswas_rajarshi_disposable.cc -I.
