#
# CSE 5441 : Lab 5
# Filename : makefile
# Author   : Rajarshi Biswas (biswas.91@osu.edu)
# 	     The Ohio State University.


all: biswas_rajarshi_lab5
biswas_rajarshi_lab5:
	mpicc -O3 -fopenmp -o lab5.out biswas_rajarshi_lab5.c ./lab5_lib/bmp_reader.o
